#pragma once
#include <bits/stdc++.h>
using namespace std;
struct J {
 using A=vector<J>;using O=map<string,J>;variant<nullptr_t,bool,long long,string,A,O> v;
 J():v(nullptr){} J(bool x):v(x){} J(int x):v((long long)x){} J(long long x):v(x){} J(string x):v(x){} J(const char*x):v(string(x)){} J(A x):v(x){} J(O x):v(x){}
 J& operator[](const string&k){if(!holds_alternative<O>(v))v=O{};return get<O>(v)[k];}const J& operator[](const string&k)const{return get<O>(v).at(k);}long long number()const{return get<long long>(v);}string text()const{return get<string>(v);}const A& array()const{return get<A>(v);}
 static J parse(const string&s){size_t i=0;function<void()>ws=[&](){while(i<s.size()&&isspace((unsigned char)s[i]))i++;};function<string()>str=[&](){ws();i++;string o;while(true){char c=s.at(i++);if(c=='"')return o;if(c=='\\'){c=s.at(i++);if(c=='n')c='\n';else if(c=='r')c='\r';else if(c=='t')c='\t';else if(c=='b')c='\b';else if(c=='f')c='\f';else if(c=='u'){int a=stoi(s.substr(i,4),nullptr,16);i+=4;c=(char)a;}}o+=c;}};function<J()>val=[&]()->J{ws();char c=s.at(i);if(c=='"')return J(str());if(c=='{'){i++;O o;ws();if(s[i]=='}'){i++;return J(o);}while(true){string k=str();ws();i++;o[k]=val();ws();if(s[i++]=='}')return J(o);}}if(c=='['){i++;A a;ws();if(s[i]==']'){i++;return J(a);}while(true){a.push_back(val());ws();if(s[i++]==']')return J(a);}}if(s.compare(i,4,"null")==0){i+=4;return J();}if(s.compare(i,4,"true")==0){i+=4;return J(true);}if(s.compare(i,5,"false")==0){i+=5;return J(false);}size_t j=i;if(s[i]=='-')i++;while(i<s.size()&&isdigit((unsigned char)s[i]))i++;return J(stoll(s.substr(j,i-j)));};return val();}
 string dump()const{if(holds_alternative<nullptr_t>(v))return "null";if(holds_alternative<bool>(v))return get<bool>(v)?"true":"false";if(holds_alternative<long long>(v))return to_string(number());if(holds_alternative<string>(v)){string o="\"";for(char c:text()){if(c=='"'||c=='\\')o+='\\';o+=c;}return o+'"';}string o;bool first=true;if(holds_alternative<A>(v)){o="[";for(auto &e:array()){if(!first)o+=",";first=false;o+=e.dump();}return o+"]";}o="{";for(auto&e:get<O>(v)){if(!first)o+=",";first=false;o+=J(e.first).dump()+":"+e.second.dump();}return o+"}";}
};
